config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  delete "/remove", to: "posts#remove_image"
  resources :tags

  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
require 'json'
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :author, :body, presence: true

  def markdownify(markdown_body)
    { author: author, body: markdown_body }.to_json
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, :body, :author, presence: true

  has_many :comments
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true

  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :markdown

  def markdown(text)
   options = {
     filter_html:     true,
     hard_wrap:       true,
     link_attributes: { rel: 'nofollow', target: "_blank" },
     space_after_headers: true,
     fenced_code_blocks: true
   }

   extensions = {
     autolink:           true,
     superscript:        true,
     disable_indented_code_blocks: true
   }

   renderer = Redcarpet::Render::HTML.new(options)
   markdown = Redcarpet::Markdown.new(renderer, extensions)

   markdown.render(text).html_safe
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json

  def create
    comment = Post.find(params[:post_id]).comments.create!(comment_params)
    respond_with comment.markdownify(markdown(comment.body)), location: ""
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @tags = Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @tags = Tag.all
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def create
    params["post"]["tag_ids"].reject!(&:blank?)
    @tags = Tag.all
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created."
      redirect_to posts_path
    else
      flash[:errors] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tags = Tag.all
  end

  def update
    params["post"]["tag_ids"].reject!(&:blank?)
    @tags = Tag.all
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "successfully updated post."
      redirect_to post_path(@post)
    else
      flash[:errors] = @post.errors.full_messages.join(', ')
      render :edit
    end
  end

  def remove_image
    post = Post.find(params[:post_id])
    post.image = nil
    post.save
    redirect_to post_path(post)
  end

  private

  def post_params
    params.require(:post).permit(:title,
                                 :body,
                                 :author,
                                 :status,
                                 :image,
                                 :tag_ids => [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag successfully created."
      redirect_to tags_path
    else
      flash[:errrors] = @tag.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogging</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  
  <%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post:</h1>

<%= form_for(@post, method: 'put') do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :status %>
  <%= f.select(:status, [['draft'], ['publish']]) %>
  <%= f.label :tags %>
  <%= f.collection_select(:tag_ids, @tags, :id, :name, {}, {multiple: true}) %><br><br>
  <%= f.file_field :image %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<div><%= link_to "Create a Post", new_post_path %></div>
<div><%= link_to "View Tags", tags_path %></div><br>
<hr>
<h2>Filtering and Ordering</h2>
<div>
  <%= text_field_tag :search, params[:search], placeholder: "Search by Title", id: "title-filter" %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by Author", id: "author-filter" %>
</div><br>
<div>
  order by: <button type="button" id="draft-posts">draft</button>
            <button type="button" id="num-of-comments"># of comments</button>
</div><br>
<div>
  filter by tag:
  <div><br>
    <button type="button" class="tag-filter">all</button>
    <% @tags.each do |tag| %>
      <button type="button" class="tag-filter"><%= tag.name %></button>
    <% end %>
  </div>
</div>
<hr>

<div class="published-posts">
  <% @posts.each do |post| %>
    <% if post.status == "publish" %>
    <div class="post" data-comments="<%= post.comments.count %>">
      <h3 class="post-title"><b>Title: </b><%= link_to post.title, post_path(post.id) %></h3>
      <h4 class="post-author">Author: <%= post.author %></h4>
      <div class="post-tags">
        <% if post.tags.any? %>
          <h5>Tags: <% post.tags.each do |tag| %>
            <span style="border:outset"><%= tag.name %></span>
          <% end %>
          </h5>
        <% end %>
      </div>
      <h5>status: published</h5>
      <%= link_to 'Edit', edit_post_path(post) %>
    </div>
    <% end %>
  <% end %>
</div>

<div class="draft-posts" style="display: none">
  <% @posts.each do |post| %>
    <% if post.status == "draft" %>
    <div class="post" data-comments="<%= post.comments.count %>">
      <h3 class="post-title"><b>Title: </b><%= link_to post.title, post_path(post.id) %></h3>
      <h4 class="post-author">Author: <%= post.author %></h4>
      <div class="post-tags">
        <% if post.tags.any? %>
          <h5>Tags: <% post.tags.each do |tag| %>
            <span style="border:outset"><%= tag.name %></span>
          <% end %>
          </h5>
        <% end %>
      </div>
      <h5>status: <%= post.status %></h5>
      <%= link_to 'Edit', edit_post_path(post) %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post:</h1>

<%= form_for(@post, url: posts_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :status %>
  <%= f.select(:status, [['draft'], ['publish']]) %>
  <%= f.label :tags %>
  <%= f.collection_select(:tag_ids, @tags, :id, :name, {}, {multiple: true}) %><br><br>
  <%= f.file_field :image %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<%= link_to "<< Back to all Posts", posts_path %>
<h1>Title: <%= @post.title %></h1>

<h2>Tags:</h2>
<div>
  <% @post.tags.each do |tag| %>
    <span style="border:outset"><%= tag.name %></span>
  <% end %>
</div>

<h3>Author: <%= @post.author %></h3>
<p>status:
    <% if @post.status == "draft" %>
      <%= @post.status %>
    <% else %>
      published
    <% end %>
</p>
<%= image_tag @post.image.url(:thumb) %>
<%= link_to "Remove Image", remove_path(post_id: @post.id), method: :delete %>
<p><%= markdown(@post.body) %></p>

<div class="comments">
  <h2>Comments:</h2>
  <% @post.comments.each do |comment| %>
  <div class="comment">
    <b><%= comment.author %></b>: <%= markdown(comment.body) %>
  </div>
  <% end %>
</div>

<h3>Add a Comment</h3>
<form class="comment-form" action="" method="post">
  <input type="hidden" id="post-id" value="<%= @post.id %>">
  <label for="comment-author">Author:</label>
  <textarea class="form-author" type="text" id="comment-author"></textarea>
  <label for="comment-author">Body:</label>
  <textarea class="form-body" type="text" id="comment-body"></textarea>
  <input id="new-comment" type="submit" value="Add Comment">
</form>

app/views/tags/index.html.erb
<%= link_to "<< Back to all Posts", posts_path %>
<h1>All Tags</h1>

<div><%= link_to "Create a Tag", new_tag_path %></div><br>

<div class="tags">
  <% @tags.each do |tag| %>
    <span style="border:outset"><%= tag.name %></span>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<%= form_for(@tag) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>